### PR TITLE
pulling swrad for SNTemp, gridded, measured SW Radiation comparison

### PR DESCRIPTION
**Pull request by jzwart**
Pulling SW Radiation from PRMS-SNTemp estimated SW radiation. 

Not sure why there are only two build-status files since all the targets were built and remake says that all targets are up-to-date.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Interesting about the build/status files! If you run `scipiper:::locate_build_status_yml('6_model_output/out/SNTemp_sw_rad_station_location_DCHI_39.73_-75.52.rds.ind')` does it identify a file, and does that file have a recent date, and/or is it in the GitHub repo already?

(For fun, I've also been getting mileage out of these recipes for scipiper exploration:
```r
# display the build/status info in the console just as it is in the file:
scipiper:::locate_build_status_yml('myfile.ind') %>% readr::read_lines() %>% cat(sep='\n')

# two equivalent calls, which I choose between based on which one I remember that day:
yaml::read_yaml(scipiper:::locate_build_status_yml('myfile.ind'))
scipiper:::get_dependency_status('myfile.ind', as_of='last_build', format='raw')

# get_dependency_status also has some other formats that can be handing when looking at several files at once.
scipiper:::get_dependency_status('myfile.ind', as_of='last_build', format='wide')
scipiper:::get_dependency_status('myfile.ind', as_of='last_build', format='long')
```
)

**Comment by jzwart** [comment]
`scipiper:::locate_build_status_yml('6_model_output/out/SNTemp_sw_rad_station_location_DCHI_39.73_-75.52.rds.ind')` does locate a file: 
```
> scipiper:::locate_build_status_yml('6_model_output/out/SNTemp_sw_rad_station_location_DCHI_39.73_-75.52.rds.ind')
[1] "build/status/Nl9tb2RlbF9vdXRwdXQvb3V0L1NOVGVtcF9zd19yYWRfc3RhdGlvbl9sb2NhdGlvbl9EQ0hJXzM5LjczXy03NS41Mi5yZHMuaW5k.yml"
```
However, I can't find this file in the build/status folder when I search manually (via windows file explorer), but I can find the hash in `.remake/objects/keys/remake_db/`

**Comment by jzwart** [comment]
```
> scipiper:::locate_build_status_yml('6_model_output/out/SNTemp_sw_rad_station_location_DCHI_39.73_-75.52.rds.ind') %>% readr::read_lines() %>% cat(sep ='\n')
Error: 'build/status/Nl9tb2RlbF9vdXRwdXQvb3V0L1NOVGVtcF9zd19yYWRfc3RhdGlvbl9sb2NhdGlvbl9EQ0hJXzM5LjczXy03NS41Mi5yZHMuaW5k.yml' does not exist in current working directory ('C:/Users/jzwart/delaware-water-temp').
> scipiper:::locate_build_status_yml('6_model_output/out/SNTemp_sw_rad_station_location_DCHI_39.73_-75.52.rds.ind') 
[1] "build/status/Nl9tb2RlbF9vdXRwdXQvb3V0L1NOVGVtcF9zd19yYWRfc3RhdGlvbl9sb2NhdGlvbl9EQ0hJXzM5LjczXy03NS41Mi5yZHMuaW5k.yml"
```

**Comment by aappling-usgs** [comment]
OK, it's coming together now. As noted in Slack, we think this may be because the build hit errors somewhere between creating these .ind files and preparing the build/status files for them.

Solution: run `scipiper:::YAMLify_build_status()` on the .ind files that should have build/status files.

**Pull request merged**
